name: CI - Tests - Nanutech

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test
