name: Run Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      # 👇 NUEVO PASO: Necesario para que SAM pueda procesar el Metadata del template
      - name: Install esbuild
        run: npm install -g esbuild
      
      - name: Install SAM CLI
        run: pip install aws-sam-cli
      
      - name: Build with SAM
        run: sam build
        continue-on-error: false 
      
      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: "--experimental-vm-modules"
