name: OWASP Security Scan

on:
  push:
    branches:
      - develop

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI
        run: npm run generate:openapi
        env:
          API_URL: ${{ secrets.API_URL_TESTING }}

      - name: Run OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: "./docs/openapi.json"
          format: openapi
          fail_action: true
